// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: message.proto

package server

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Migration     string                 `protobuf:"bytes,2,opt,name=migration,proto3" json:"migration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreate) Reset() {
	*x = RequestCreate{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreate) ProtoMessage() {}

func (x *RequestCreate) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreate.ProtoReflect.Descriptor instead.
func (*RequestCreate) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestCreate) GetMigration() string {
	if x != nil {
		return x.Migration
	}
	return ""
}

type RequestGetDrop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetDrop) Reset() {
	*x = RequestGetDrop{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetDrop) ProtoMessage() {}

func (x *RequestGetDrop) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetDrop.ProtoReflect.Descriptor instead.
func (*RequestGetDrop) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGetDrop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RequestQueryExec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Args          []*anypb.Any           `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQueryExec) Reset() {
	*x = RequestQueryExec{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQueryExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryExec) ProtoMessage() {}

func (x *RequestQueryExec) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryExec.ProtoReflect.Descriptor instead.
func (*RequestQueryExec) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *RequestQueryExec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestQueryExec) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RequestQueryExec) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type DDLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDLResponse) Reset() {
	*x = DDLResponse{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDLResponse) ProtoMessage() {}

func (x *DDLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDLResponse.ProtoReflect.Descriptor instead.
func (*DDLResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *DDLResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ResponseQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseQuery) Reset() {
	*x = ResponseQuery{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQuery) ProtoMessage() {}

func (x *ResponseQuery) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseQuery.ProtoReflect.Descriptor instead.
func (*ResponseQuery) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseQuery) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResponseExec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseExec) Reset() {
	*x = ResponseExec{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseExec) ProtoMessage() {}

func (x *ResponseExec) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseExec.ProtoReflect.Descriptor instead.
func (*ResponseExec) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseExec) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\x1a\x19google/protobuf/any.proto\"A\n" +
	"\rRequestCreate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tmigration\x18\x02 \x01(\tR\tmigration\"$\n" +
	"\x0eRequestGetDrop\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"f\n" +
	"\x10RequestQueryExec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12(\n" +
	"\x04args\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\x04args\"\x1f\n" +
	"\vDDLResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"'\n" +
	"\rResponseQuery\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"&\n" +
	"\fResponseExec\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result2\xb1\x02\n" +
	"\n" +
	"PopService\x128\n" +
	"\x06Create\x12\x16.message.RequestCreate\x1a\x14.message.DDLResponse\"\x00\x126\n" +
	"\x03Get\x12\x17.message.RequestGetDrop\x1a\x14.message.DDLResponse\"\x00\x127\n" +
	"\x04Drop\x12\x17.message.RequestGetDrop\x1a\x14.message.DDLResponse\"\x00\x12<\n" +
	"\x05Query\x12\x19.message.RequestQueryExec\x1a\x16.message.ResponseQuery\"\x00\x12:\n" +
	"\x04Exec\x12\x19.message.RequestQueryExec\x1a\x15.message.ResponseExec\"\x00B\x10Z\x0ebedroompop/popb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_proto_goTypes = []any{
	(*RequestCreate)(nil),    // 0: message.RequestCreate
	(*RequestGetDrop)(nil),   // 1: message.RequestGetDrop
	(*RequestQueryExec)(nil), // 2: message.RequestQueryExec
	(*DDLResponse)(nil),      // 3: message.DDLResponse
	(*ResponseQuery)(nil),    // 4: message.ResponseQuery
	(*ResponseExec)(nil),     // 5: message.ResponseExec
	(*anypb.Any)(nil),        // 6: google.protobuf.Any
}
var file_message_proto_depIdxs = []int32{
	6, // 0: message.RequestQueryExec.args:type_name -> google.protobuf.Any
	0, // 1: message.PopService.Create:input_type -> message.RequestCreate
	1, // 2: message.PopService.Get:input_type -> message.RequestGetDrop
	1, // 3: message.PopService.Drop:input_type -> message.RequestGetDrop
	2, // 4: message.PopService.Query:input_type -> message.RequestQueryExec
	2, // 5: message.PopService.Exec:input_type -> message.RequestQueryExec
	3, // 6: message.PopService.Create:output_type -> message.DDLResponse
	3, // 7: message.PopService.Get:output_type -> message.DDLResponse
	3, // 8: message.PopService.Drop:output_type -> message.DDLResponse
	4, // 9: message.PopService.Query:output_type -> message.ResponseQuery
	5, // 10: message.PopService.Exec:output_type -> message.ResponseExec
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
